version: "2"

run:
  timeout: 5m
  tests: false

issues:
  max-issues-per-linter: 0 # unlimited
  max-same-issues: 50
  new: false # show all issues, not just new ones

linters:
  default: all
  disable:
    - wsl
    - wsl_v5
    - err113
    - prealloc
    - noinlineerr
    - exhaustruct
  settings:
    goconst:
      min-occurrences: 4
      match-constant: true
    varnamelen:
      ignore-names:
        - err
        - ok
        - i
        - j
        - g # generator parameter
        - id
    mnd:
      ignored-functions:
        - "strings.SplitN"
        - "os.WriteFile"
    forbidigo:
      forbid:
        - pattern: "^(print|println)$"
    tagliatelle:
      case:
        rules:
          avro: snake
          bson: snake
          env: upperSnake
          envconfig: upperSnake
          json: snake
          mapstructure: snake
          xml: snake
          yaml: snake

    depguard:
      rules:
        pkgerr:
          deny:
            - pkg: github.com/pkg/errors
              desc: Use errors instead of pkg/errors
    dupl:
      threshold: 100
    errcheck:
      check-type-assertions: false
      check-blank: false
    funlen:
      lines: 320
      statements: 120
    cyclop:
      max-complexity: 15
      package-average: 0
    gocognit:
      min-complexity: 110
    gocyclo:
      min-complexity: 65
    lll:
      line-length: 270
    misspell:
      locale: US
    nolintlint:
      require-explanation: false
      require-specific: false
      allow-unused: false
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - dupl
          - errcheck
          - gocyclo
          - gosec
        path: _mock\.go
      - linters:
          - gocritic
        text: deprecatedComment
      - linters:
          - gocritic
        text: commentedOutCode
      - linters:
          - lll
        source: ^\s+// [(http(s)?):\/\/(www\.)?a-zA-Z0-9@:%._\+~#=]{2,256}\.[a-z]{2,6}\b[-a-zA-Z0-9@:%_\+.~#?&//=]*
      - linters:
          - lll
        source: "^//go:generate "
    paths:
      - integration_tests/
formatters:
  enable:
    - gci
    - gofumpt
    - gofmt
    - goimports
    - golines
  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(github.com/oter/dotprompt-gen-go)
    gofumpt:
      module-path: github.com/oter/dotprompt-gen-go
      extra-rules: true
    gofmt:
      simplify: true
      rewrite-rules:
        - pattern: "interface{}"
          replacement: "any"
        - pattern: "a[b:len(a)]"
          replacement: "a[b:]"
    goimports:
      local-prefixes:
        - github.com/oter/dotprompt-gen-go
    golines:
      max-len: 200
  exclusions:
    generated: lax
