version: "3"

silent: false

vars:
  BINARY_NAME: dotprompt-gen-go
  BUILD_DIR: .bin
  MAIN_PACKAGE: ./cmd/dotprompt-gen-go
  VERSION_PKG: github.com/oter/dotprompt-gen-go/internal/generator

tasks:
  default:
    desc: Show available tasks
    cmds:
      - task --list

  version:
    desc: Show the version that will be used for builds
    vars:
      VERSION:
        sh: git describe --tags --always --dirty 2>/dev/null || echo "dev"
    cmds:
      - echo "Version {{.VERSION}}"

  modernize:
    desc: Modernize the codebase
    cmds:
      - go run golang.org/x/tools/gopls/internal/analysis/modernize/cmd/modernize@latest -fix -test ./...
      - go run golang.org/x/tools/gopls/internal/analysis/simplifyrange/cmd/simplifyrange@latest -fix -test ./...

  generate:
    desc: Generate code from prompt files
    cmds:
      - go generate ./...

  build:
    desc: Build the binary
    deps:
      - generate
    vars:
      VERSION:
        sh: git describe --tags --always --dirty 2>/dev/null || echo "dev"
    cmds:
      - mkdir -p {{.BUILD_DIR}}
      - go build -ldflags "-X {{.VERSION_PKG}}.Version={{.VERSION}}" -o {{.BUILD_DIR}}/{{.BINARY_NAME}} {{.MAIN_PACKAGE}}
      - echo "Built {{.BINARY_NAME}} version {{.VERSION}}"
    generates:
      - "{{.BUILD_DIR}}/{{.BINARY_NAME}}"

  build-release:
    desc: Build release binary with optimizations
    vars:
      VERSION:
        sh: git describe --tags --always --dirty 2>/dev/null || echo "dev"
    cmds:
      - mkdir -p {{.BUILD_DIR}}
      - go build -ldflags "-s -w -X {{.VERSION_PKG}}.Version={{.VERSION}}" -o {{.BUILD_DIR}}/{{.BINARY_NAME}} {{.MAIN_PACKAGE}}
      - echo "Built release {{.BINARY_NAME}} version {{.VERSION}}"
    generates:
      - "{{.BUILD_DIR}}/{{.BINARY_NAME}}"

  test:
    desc: Run tests
    cmds:
      - go test -v ./...

  test-coverage:
    desc: Run tests with coverage
    cmds:
      - go test -v -race -coverprofile=coverage.out ./...
      - go tool cover -html=coverage.out -o coverage.html
      - echo "Coverage report generated at coverage.html"

  clean:
    desc: Clean build artifacts
    cmds:
      - rm -rf {{.BUILD_DIR}}
      - rm -f coverage.out coverage.html

  deps:
    desc: Download dependencies
    cmds:
      - go mod download
      - go mod tidy

  fmt:
    desc: Format code using golangci-lint formatters
    cmds:
      - golangci-lint run --fix

  lint:
    desc: Run golangci-lint
    cmds:
      - golangci-lint run

  lint-fix:
    desc: Run golangci-lint with auto-fix
    cmds:
      - golangci-lint run --fix

  check:
    desc: Run all checks (lint, test)
    deps:
      - lint
      - test

  run:
    desc: Run the application with example arguments
    cmds:
      - go run {{.MAIN_PACKAGE}} -h

  dev:
    desc: Development workflow - lint with fix, test, and build
    deps:
      - lint-fix
      - test
      - build
