// Code generated by dotprompt-gen-go dev. DO NOT EDIT.

package examples

import "fmt"

// ValidationTagsInput represents the input for validation tags
type ValidationTagsInput struct {
	// Username for the account
	UserName string `json:"user_name" validate:"required,min=3,max=50"`
	// User email address
	Email string `json:"email" validate:"required,email"`
	// User age
	Age int `json:"age" validate:"required,min=18,max=120"`
	// Optional user biography
	Bio         string      `json:"bio" validate:"max=500"`
	Preferences Preferences `json:"preferences"`
}

// Preferences represents
type Preferences struct {
	// Enable notifications
	Notifications bool `json:"notifications"`
	// UI theme preference
	Theme string `json:"theme" validate:"oneof=light dark auto"`
}

// ValidationTagsOutput represents the output for validation tags
type ValidationTagsOutput struct {
	// Generated user ID
	UserId *string `json:"user_id" validate:"required,uuid4"`
	// Account status
	Status *StatusEnum `json:"status"`
	// Account creation timestamp
	CreatedAt *string `validate:"required" db:"created_at" json:"created_at,omitempty"`
}

// StatusEnum represents valid status values
type StatusEnum string

const (
	StatusEnumActive    StatusEnum = "active"
	StatusEnumPending   StatusEnum = "pending"
	StatusEnumSuspended StatusEnum = "suspended"
)

// Validate checks if the StatusEnum value is valid
func (e StatusEnum) Validate() error {
	switch e {
	case StatusEnumActive, StatusEnumPending, StatusEnumSuspended:
		return nil
	default:
		return fmt.Errorf("invalid StatusEnum value: %q, must be one of: active, pending, suspended", string(e))
	}
}
