// Code generated by dotprompt-gen-go dev. DO NOT EDIT.

package prompts

// ArrayTypesInput represents the input for array types
type ArrayTypesInput struct {
	// List of tags
	Tags []string `json:"tags"`
	// List of scores
	Scores []float64 `json:"scores"`
	// List of IDs
	Ids []int `json:"ids"`
}

// ArrayTypesOutput represents the output for array types
type ArrayTypesOutput struct {
	// Processed results
	Results []string `json:"results"`
	// Result counts
	Counts []int `json:"counts"`
}

// Validate validates all fields in ArrayTypesInput
func (s ArrayTypesInput) Validate() error {
	return nil
}

// Validate validates all fields in ArrayTypesOutput
func (s ArrayTypesOutput) Validate() error {
	return nil
}
