// Code generated by dotprompt-gen-go dev. DO NOT EDIT.

package prompts

import "fmt"
import "github.com/oter/dotprompt-gen-go/pkg/validator"

// ClassifyHabitsInput represents the input for classify habits
type ClassifyHabitsInput struct {
	// The habit description to classify
	Habit string `json:"habit"`
}

// ClassifyHabitsOutput represents the output for classify habits
type ClassifyHabitsOutput struct {
	// insightful explanation of why this habit fits the category
	Explanation string `json:"explanation"`
	// The developmental stage this habit represents
	ImpactLevel ImpactLevelEnum `json:"impact_level"`
	// The transformative category of the habit
	TransformationCategory TransformationCategoryEnum `json:"transformation_category"`
}

// Validate validates all fields in ClassifyHabitsInput
func (s ClassifyHabitsInput) Validate() error {
	return nil
}

// Validate validates all fields in ClassifyHabitsOutput
func (s ClassifyHabitsOutput) Validate() error {
	fieldValidations := map[string]validator.Validator{
		"impact_level":            s.ImpactLevel,
		"transformation_category": s.TransformationCategory,
	}
	return validator.ValidateFields(fieldValidations)
}

// ImpactLevelEnum represents valid impact_level values
type ImpactLevelEnum string

const (
	ImpactLevelEnumFoundational ImpactLevelEnum = "foundational"
	ImpactLevelEnumGrowth       ImpactLevelEnum = "growth"
	ImpactLevelEnumMastery      ImpactLevelEnum = "mastery"
)

// Validate checks if the ImpactLevelEnum value is valid
func (e ImpactLevelEnum) Validate() error {
	switch e {
	case ImpactLevelEnumFoundational, ImpactLevelEnumGrowth, ImpactLevelEnumMastery:
		return nil
	default:
		return fmt.Errorf("invalid ImpactLevelEnum value: %q, must be one of: foundational, growth, mastery", string(e))
	}
}

// TransformationCategoryEnum represents valid transformation_category values
type TransformationCategoryEnum string

const (
	TransformationCategoryEnumPhysicalVitality       TransformationCategoryEnum = "physical_vitality"
	TransformationCategoryEnumMentalMastery          TransformationCategoryEnum = "mental_mastery"
	TransformationCategoryEnumCreativeExpression     TransformationCategoryEnum = "creative_expression"
	TransformationCategoryEnumSocialConnection       TransformationCategoryEnum = "social_connection"
	TransformationCategoryEnumFinancialWisdom        TransformationCategoryEnum = "financial_wisdom"
	TransformationCategoryEnumEnvironmentalHarmony   TransformationCategoryEnum = "environmental_harmony"
	TransformationCategoryEnumSpiritualGrowth        TransformationCategoryEnum = "spiritual_growth"
	TransformationCategoryEnumProfessionalExcellence TransformationCategoryEnum = "professional_excellence"
	TransformationCategoryEnumLearningAdventure      TransformationCategoryEnum = "learning_adventure"
	TransformationCategoryEnumSelfCareRitual         TransformationCategoryEnum = "self_care_ritual"
	TransformationCategoryEnumMindfulPresence        TransformationCategoryEnum = "mindful_presence"
)

// Validate checks if the TransformationCategoryEnum value is valid
func (e TransformationCategoryEnum) Validate() error {
	switch e {
	case TransformationCategoryEnumPhysicalVitality, TransformationCategoryEnumMentalMastery, TransformationCategoryEnumCreativeExpression, TransformationCategoryEnumSocialConnection, TransformationCategoryEnumFinancialWisdom, TransformationCategoryEnumEnvironmentalHarmony, TransformationCategoryEnumSpiritualGrowth, TransformationCategoryEnumProfessionalExcellence, TransformationCategoryEnumLearningAdventure, TransformationCategoryEnumSelfCareRitual, TransformationCategoryEnumMindfulPresence:
		return nil
	default:
		return fmt.Errorf("invalid TransformationCategoryEnum value: %q, must be one of: physical_vitality, mental_mastery, creative_expression, social_connection, financial_wisdom, environmental_harmony, spiritual_growth, professional_excellence, learning_adventure, self_care_ritual, mindful_presence", string(e))
	}
}
