// Code generated by dotprompt-gen-go dev. DO NOT EDIT.

package prompts

// JsonSchemaArraysInput represents the input for json schema arrays
type JsonSchemaArraysInput struct {
	// List of keywords
	Keywords []string `json:"keywords"`
	// List of ratings
	Ratings []float64 `json:"ratings"`
}

// JsonSchemaArraysOutput represents the output for json schema arrays
type JsonSchemaArraysOutput struct {
	// Keywords that matched
	MatchedKeywords []string `json:"matched_keywords"`
	// Average of all ratings
	AverageRating *float64 `json:"average_rating"`
}

// Validate validates all fields in JsonSchemaArraysInput
func (s JsonSchemaArraysInput) Validate() error {
	return nil
}

// Validate validates all fields in JsonSchemaArraysOutput
func (s JsonSchemaArraysOutput) Validate() error {
	return nil
}
