// Code generated by dotprompt-gen-go dev. DO NOT EDIT.

package prompts

import "fmt"
import "github.com/oter/dotprompt-gen-go/pkg/validator"

// MixedFormatsInput represents the input for mixed formats
type MixedFormatsInput struct {
	Preferences any      `json:"preferences"`
	Role        RoleEnum `json:"role"`
	Settings    any      `json:"settings"`
	UserId      string   `json:"user_id"`
}

// MixedFormatsOutput represents the output for mixed formats
type MixedFormatsOutput struct {
	Recommendations []string    `json:"recommendations"`
	Success         bool        `json:"success"`
	UserProfile     UserProfile `json:"user_profile"`
}

// UserProfile represents
type UserProfile struct {
	Id       *string       `json:"id"`
	UserRole *UserRoleEnum `json:"user_role"`
}

// Validate validates all fields in MixedFormatsInput
func (s MixedFormatsInput) Validate() error {
	fieldValidations := map[string]validator.Validator{
		"role": s.Role,
	}
	return validator.ValidateFields(fieldValidations)
}

// Validate validates all fields in MixedFormatsOutput
func (s MixedFormatsOutput) Validate() error {
	fieldValidations := map[string]validator.Validator{
		"user_profile": s.UserProfile,
	}
	return validator.ValidateFields(fieldValidations)
}

// Validate validates all fields in UserProfile
func (s UserProfile) Validate() error {
	fieldValidations := map[string]validator.Validator{
		"user_role": s.UserRole,
	}
	return validator.ValidateFields(fieldValidations)
}

// RoleEnum represents valid role values
type RoleEnum string

const (
	RoleEnumAdmin RoleEnum = "admin"
	RoleEnumUser  RoleEnum = "user"
	RoleEnumGuest RoleEnum = "guest"
)

// Validate checks if the RoleEnum value is valid
func (e RoleEnum) Validate() error {
	switch e {
	case RoleEnumAdmin, RoleEnumUser, RoleEnumGuest:
		return nil
	default:
		return fmt.Errorf("invalid RoleEnum value: %q, must be one of: admin, user, guest", string(e))
	}
}

// UserRoleEnum represents valid user_role values
type UserRoleEnum string

const (
	UserRoleEnumAdmin UserRoleEnum = "admin"
	UserRoleEnumUser  UserRoleEnum = "user"
	UserRoleEnumGuest UserRoleEnum = "guest"
)

// Validate checks if the UserRoleEnum value is valid
func (e UserRoleEnum) Validate() error {
	switch e {
	case UserRoleEnumAdmin, UserRoleEnumUser, UserRoleEnumGuest:
		return nil
	default:
		return fmt.Errorf("invalid UserRoleEnum value: %q, must be one of: admin, user, guest", string(e))
	}
}
